---
name: Folding@home
version: dev
slug: foldingathome
description: Fighting disease with a world wide distributed super computer
url: https://github.com/jbecker-it/ha-addon-foldingathome-rpi5
codenotary: codenotary@frenck.dev
webui: http://[HOST]:[PORT:7396]
arch:
  - aarch64
init: false
hassio_api: true
video: true
ports:
  7396/tcp: 7396
  36330/tcp: null
ports_description:
  7396/tcp: Web interface
  36330/tcp: Remote command interface
